### ISSUE TITLE
API - Create new post

### ISSUE THREAD

**Issue by ThanhDuyPhan** [Ginkgo-App/ginkgo-webservice#18]
https://app.swaggerhub.com/apis-docs/Hieren/Ginkgo/1.0#/Post/post-posts

**Comment by hienlh** [comment]
Sửa những comment này 

https://github.com/Ginkgo-App/ginkgo-webservice/commit/ff10449fce0c8dc7a0aa9c8e53c5849c925ec1be#commitcomment-40018416

**Comment by hienlh** [comment]
Api lỗi
![DeepinScreenshot_select-area_20200620115053.png](https://images.zenhubusercontent.com/5c79f12fcfa1d10365962aa0/6561eac4-d4d8-4202-a9e1-843065674a68)

**Comment by hienlh** [comment]
Lỗi khác 
![DeepinScreenshot_select-area_20200621095258.png](https://images.zenhubusercontent.com/5c79f12fcfa1d10365962aa0/a0428db5-8135-43a5-b549-9c6992da80f0)

**Comment by ThanhDuyPhan** [comment]
Đã fix

**Comment by hienlh** [comment]
> Đã fix
Thiếu validate, chỉ gửi lên tour ID ko gửi lên rating mà vẫn đc 
![DeepinScreenshot_select-area_20200621220356](https://user-images.githubusercontent.com/36977998/85228028-24026c80-b40b-11ea-8be1-8087ff642a51.png)
