### ISSUE TITLE
API - Get post by user

### ISSUE THREAD

**Issue by ThanhDuyPhan** [Ginkgo-App/ginkgo-webservice#19]

**Comment by hienlh** [comment]
@ThanhDuyPhan Làm endpoint nào á, t thử 2 cái me với user 404

**Comment by hienlh** [comment]
Sửa lại follow swagger. (Chú ý trường IsLiked)
https://app.swaggerhub.com/apis-docs/Hieren/Ginkgo/1.0#/Post/get-users-me-posts
https://app.swaggerhub.com/apis-docs/Hieren/Ginkgo/1.0#/Post/get_users__id__posts

**Comment by ThanhDuyPhan** [comment]
FeaturedComment - trường này làm gì vậy?

**Comment by hienlh** [comment]
Bình luận nổi bật

**Comment by ThanhDuyPhan** [comment]
Mà lấy tourInfo để làm gì vậy?

**Comment by hienlh** [comment]
> Mà lấy tourInfo để làm gì vậy?

Nói gì vậy?

**Comment by ThanhDuyPhan** [comment]
Nhầm tí

**Comment by hienlh** [comment]
Không cần trả về lỗi này Post not found
Trả về list rỗng để dưới app hiển thị not found

**Comment by hienlh** [comment]
Comment đang thiếu author

![DeepinScreenshot_select-area_20200628103343.png](https://images.zenhubusercontent.com/5c79f12fcfa1d10365962aa0/b4f22e27-7a23-4a1f-91a9-ea19b2686d5e)

**Comment by hienlh** [comment]
Tour ở đây phải là dạng simple tour

![DeepinScreenshot_select-area_20200628161858.png](https://images.zenhubusercontent.com/5c79f12fcfa1d10365962aa0/e7fff9c2-5c7b-41c9-8e51-4ab2469dad93)

**Comment by hienlh** [comment]
Total comment đang bị thiếu 1.
ví dụ 3 comment thì total comment trả về 2

**Comment by hienlh** [comment]
IsLike đang bị sai.

Đăng nhập bằng nick admin@ginkgo.com. Get posts của user 44 là **Nguyên Culi**.
Rõ ràng trong db chỉ có **Nguyên Culi** like bài viết của mình nhưng giá trị trả về thì user admin cũng đang like bài viết 

![DeepinScreenshot_select-area_20200629220427.png](https://images.zenhubusercontent.com/5c79f12fcfa1d10365962aa0/33cfc9fc-4189-452c-ae19-e3f426f6c01c)

**Comment by hienlh** [comment]
> IsLike đang bị sai.
> 
> Đăng nhập bằng nick [admin@ginkgo.com](mailto:admin@ginkgo.com). Get posts của user 44 là **Nguyên Culi**.
> Rõ ràng trong db chỉ có **Nguyên Culi** like bài viết của mình nhưng giá trị trả về thì user admin cũng đang like bài viết
> 
> ![DeepinScreenshot_select-area_20200629220427.png](https://camo.githubusercontent.com/78696f93e987568d1336fc09f9db7101735098ab/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563373966313266636661316431303336353936326161302f33336366633966632d343138392d343532632d616531392d653366343236663663303163)

Lưu ý user m cần get post và user đang get là khác nhau. Sai chỗ t khoanh đỏ 
![DeepinScreenshot_select-area_20200629220951](https://user-images.githubusercontent.com/36977998/86023083-681dee80-ba55-11ea-95e8-f40b2a23e34d.png)

**Comment by ThanhDuyPhan** [comment]
> Khi comment hay like, thay vì m chỉ cộng 1 vào tổng hiện tại thì m nên count table comment và like sau đó +1 thì dữ liệu sẽ đc đồng bộ tránh sai

T đang tính sửa thành vậy á

**Comment by ThanhDuyPhan** [comment]
OK để check lại
