### ISSUE TITLE
Create tour API

### ISSUE THREAD

**Issue by hienlh** [Ginkgo-App/ginkgo-webservice#21]

**Comment by hienlh** [comment]
Lỗi khi tạo tour
![DeepinScreenshot_select-area_20200615215704.png](https://images.zenhubusercontent.com/5c79f12fcfa1d10365962aa0/408068d8-41c5-4d39-b849-eda338ad4f72)

**Comment by ThanhDuyPhan** [comment]
Lỗi bị trùng khóa chình, để check lại

**Comment by hienlh** [comment]
Không nhận tour timline detail

![DeepinScreenshot_select-area_20200704021026.png](https://images.zenhubusercontent.com/5c79f12fcfa1d10365962aa0/04f13738-ba37-441a-a84b-7fb06fd74178)

**Comment by ThanhDuyPhan** [comment]
Bị đụng PK rồi, để check lại
