### ISSUE TITLE
Get Tour Detail API

### ISSUE THREAD

**Issue by hienlh** [Ginkgo-App/ginkgo-webservice#22]
https://app.swaggerhub.com/apis-docs/Hieren/Ginkgo/1.0#/Tour/get-tours-id

**Comment by hienlh** [comment]
Sửa lại endpoint và response schema

**Comment by hienlh** [comment]
Thêm dữ liệu cho mấy cái này

![DeepinScreenshot_select-area_20200627184405.png](https://images.zenhubusercontent.com/5c79f12fcfa1d10365962aa0/b3d84768-4a11-4df3-8fd5-980d81ddac4e)

**Comment by ThanhDuyPhan** [comment]
Sửa rồi nha

**Comment by hienlh** [comment]
> Sửa rồi nha

Thiếu joinAt và acceptedAt

**Comment by hienlh** [comment]
Thiếu place trong timeline detail

![DeepinScreenshot_select-area_20200701060510.png](https://images.zenhubusercontent.com/5c79f12fcfa1d10365962aa0/81fe4369-1fd4-4c9b-90b6-6ceb0bbe2941)
