### ISSUE TITLE
Like & unlike post api

### ISSUE THREAD

**Issue by hienlh** [Ginkgo-App/ginkgo-webservice#32]

**Comment by hienlh** [comment]
Lỗi 
![DeepinScreenshot_select-area_20200628172022.png](https://images.zenhubusercontent.com/5c79f12fcfa1d10365962aa0/a0176d39-4568-45e6-a6e1-de4c3b8338cb)

**Comment by ThanhDuyPhan** [comment]
Gửi có nhầm gì không? T gửi bình thường mà

**Comment by hienlh** [comment]
> Gửi có nhầm gì không? T gửi bình thường mà

Hình t gửi đầy đủ thông tin đó, lên swagger mà thử đi

**Comment by ThanhDuyPhan** [comment]
Đã fix
